### ISSUE TITLE
TypeError: load_platform() missing 2 required positional arguments

### ISSUE THREAD

**Issue by jjanderson** [philmottin/ha-opensprinkler#4]
Hello,

Following a recent upgrade to HA, (possibly to 0.80, but not entirely sure which exact version is resulting in the error) I am getting the follwing invalid config error:

```
ERROR (MainThread) [homeassistant.setup] Error during setup of component opensprinkler
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/opensprinkler.py", line 99, in setup
    load_platform(hass, 'scene', DOMAIN)
TypeError: load_platform() missing 2 required positional arguments: 'discovered' and 'hass_config'
```

**Comment by Mattat01** [comment]
I found that this worked for me, but I'm not sure if it breaks anything else I haven't noticed: https://community.home-assistant.io/t/integrate-with-opensprinkler/18142/63

For some reason my controller card doesn't have the sliders, but I doubt this is related.

Cheers,
Matthew
